### ISSUE TITLE
The function wfGetDB() is being phased out and should not be used in new code

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#10]
Replace: 
$dbw = wfGetDB( DB_MASTER );

WITH
$lb = MediaWikiServices::getInstance()->getDBLoadBalancer();
$dbw = $lb->getConnectionRef( DB_PRIMARY );

**Comment by rht** [comment]
Reminder that the Cargo extension still uses `wfGetDB` as well, and so is a room for contribution. If @dykstranet wants to make a PR to MediaWiki using their Gerrit system.

**Comment by FantasticoFox** [comment]
via matrix from: rht
figured the problem
there are 2 issues
you need use MediaWiki\MediaWikiServices;
you need to use DB_MASTER, not DB_PRIMARY
we need to investigate why DB_PRIMARY doesn't exist yet, otherwise we can't make a pr to the cargo extension
if you wonder how i found the error: i read the error msg in the html output of the curl. i think it is much better that you type the url in the browser instead of curl, so you can see the error message clearly
use curl only for POST requests

**Comment by FantasticoFox** [comment]
TODO: Investgate why DB_PRIMARY does not work yet.

**Comment by rht** [comment]
> TODO: Investgate why DB_PRIMARY does not work yet.

The reason why `DB_PRIMARY` still does not work is that it is only exists in current development version of Mediawiki post-1.35.2.
If you look at the code at version 1.35.2, you see that it is still `DB_MASTER`: https://github.com/wikimedia/mediawiki/blob/e5823c068a2e0d8af72538fe5cd152ddb43c58e9/includes/libs/rdbms/defines.php.

**Comment by FantasticoFox** [comment]
I updated the HashWriterHook to use the new version. This was our last usage in our code. Closing the issue with the PR.
