### ISSUE TITLE
PageContentSaveComplete: legacy hook, deprecated in favor of this one

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#11]
Depreciated: 
https://www.mediawiki.org/wiki/Manual:Hooks/PageContentSaveComplete

New way / replace with:
mediawiki.org/wiki/Manual:Hooks/PageSaveComplete

**Comment by rht** [comment]
We use https://www.mediawiki.org/wiki/Manual:Hooks/RevisionFromEditComplete, not that one. And this one is the newer version of the deprecated https://www.mediawiki.org/wiki/Manual:Hooks/NewRevisionFromEditComplete.

**Comment by FantasticoFox** [comment]
Issue obsolete. Close.
