### ISSUE TITLE
EPIC: Export / Import Verified Page History

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#16]
ExtensionDataAccounting Releases V2.X
	
The standard 'export page' function does not include additional datafields included in the tables added by the extension. By creating an updated version of export page history we are able to export all required data for a page verification in another wiki which is importing the verified page. This is a critical functionality to exchange pages.

**Comment by rht** [comment]
@FantasticoFox there should be a link to a commit / PR that closes the issue.

**Comment by rht** [comment]
https://github.com/FantasticoFox/ExtensionDataAccounting/commit/e2ababec91028c3624d3b11b4b2753d8cfe131e0
