### ISSUE TITLE
Extract public key from signed page

### ISSUE THREAD

**Issue by rht** [FantasticoFox/ExtensionDataAccounting#32]
There are 2 ways to do this:
- https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/modules/_signature_.md#const-ecrecover (returns public key)
- https://github.com/MetaMask/eth-sig-util#recoverpersonalsignature-msgparams (returns Ethereum address) but Metamask also has https://github.com/MetaMask/eth-sig-util#extractpublickey-msgparams which returns public key.

**Comment by FantasticoFox** [comment]
Done

**Comment by rht** [comment]
https://github.com/FantasticoFox/ExtensionDataAccounting/commit/2a5ba75d8291f5b5d0051f0ee378dc24cff73eee
