### ISSUE TITLE
Metamask requires message to be either in '[ ]' or quotations to not alter the string for signing

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#33]
![MetaMask Notification_042](https://user-images.githubusercontent.com/45313235/119247531-de22cb00-bbbc-11eb-8cad-7b09325a3bce.png)

To avoid this we currently use square brackets or quotations.

**Comment by FantasticoFox** [comment]
While message is displayed WRONGLY it does actually work fine when storing the message. So in the DB there is no strange string interpretation and the data looks clean.

**Comment by FantasticoFox** [comment]
If string starts with 0x it will be interpreted as a hex encoded binary. So putting some padding around it seems to be the only viable solution. Combining it with making it more useful for the user to read makes sense.

**Comment by rht** [comment]
https://github.com/FantasticoFox/ExtensionDataAccounting/commit/0e2ed3f8aaa5790cda04259dad96b704c299814a
