### ISSUE TITLE
Clarification: Is the sign button javascript loaded only on the save page display 

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#6]
or in all contexts specified 'BeforePageDisplay', 'ParserFirstCallIni' etc?
See 'Hooks' in extension.js

**Comment by ipatka** [comment]
The Sign button is now loaded on the revision history page
![Screen Shot 2021-05-20 at 11 51 29 AM](https://user-images.githubusercontent.com/4401444/119273115-63b37480-bbd7-11eb-9c7e-733f9877ad39.png)
