### ISSUE TITLE
[Witness][BUG] witness_event_verification_hash is incorrectly calculated

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#62]
LOGIC getHashSum(page_manifest_verification_hash.merkle_root) 
EXAMPLE getHashSum(7f0ac1e1b022e615402033f1c987437d646210799e8d602c1a52049a53c64c4e31c823361d1b8805f1f11ca032075b91c836650f1b47ed147cf5e86833f99404b9d75144c1af9cc762c90cb7aa276d29b083e4a9aa0022faee77dfeb967c0221f64242aa149bd20893b6729be654a4982f0e09f01330ba69478983918180945d)

Expected result: d5f4d33841b0f7b2349bb7fbb1ac65bad3a18d5a1680636387cbfef000be0ffb58b0471d6589e5713af44697606d65e1e2ddc3bf6fbad012d29159e76f044c30
Factual result: 8ab411c36d27adc2e364fd8e449f89dc1463b272dbe80ebfb3a37b5beb183e70dbd5a8daa24c506825007cf2ecdf22c06b950b4e622c3fce545e45abce4a2baf
![image](https://user-images.githubusercontent.com/45313235/126129385-bbf95771-1a85-4243-88bd-bb5247059ee5.png)

**Comment by FantasticoFox** [comment]
Code in SpecialPage:Witness

**Comment by rht** [comment]
That's because the hasher option in SpecialWitness.php and HashWriterHooks are inconsistent.
In the former:
```php
		$hasher = function ($data) {
			return hash('sha3-512', $data, false);
		};
```
The latter:
```php
function getHashSum($inputStr) {
    return hash("sha3-512", $inputStr);
}
```
You have to choose which version to use.

**Comment by FantasticoFox** [comment]
Added 3rd variable for the function to be false as well. Solved the issue.

**Comment by rht** [comment]
The problem was that merkle_root accidentally contains extra html stuff because the substr range isn't correct. But we're not using substr anyway because the length of the hash could change in the future (with different hashing function), and we want to make it independent of hashing function.
