### ISSUE TITLE
[BUG] Importer does not work anymore after we removed 'debugging' field from the page_verification table

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#67]

**Comment by FantasticoFox** [comment]
Solution Print the debug to $wfdebug instead

**Comment by rht** [comment]
Fixed in https://github.com/FantasticoFox/ExtensionDataAccounting/commit/13ce0a46e380c1e8a23f484f5a954ba3ace228aa
