### ISSUE TITLE
Specify and redesign RESTAPI to interface with Metamask

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/ExtensionDataAccounting#8]

**Comment by FantasticoFox** [comment]
Cleanup: use pot. only one parameter for RESTAPI.

**Comment by rht** [comment]
I thought we need another API endpoint for requesting the verification hash? So in total 2 API commands for now?

**Comment by FantasticoFox** [comment]
This is correct. Something like this:

Module:PageVerification: GET (page_title(String), revision ID (INT), Retrieve $VerificationHash), METHOD:CALL_VHASH);
Module:PageVerification: GET (Signature, PublicKey),(METHOD: SEND_MM_Data);

**Comment by FantasticoFox** [comment]
Refactoring the API gives now a vast set of new options to query our extension.
